### ISSUE TITLE
安卓4.4盒子打开后无法使用遥控器控制

### ISSUE THREAD

**Issue by 0xCP** [sifacaii/VlcJellyfin#1]
作者你好，

在安装本项目releases里的apk文件后，打开显示为普通浏览器界面，只能使用鼠标进行操作，无法使用遥控器执行操作。
请问是否有开关能将界面设置成AndroidTV模式，从而使用遥控器进行控制和选择？

设备：新魔百和 Android 4.4

**Comment by sifacaii** [comment]
这个最高支持到10.6.4

**Comment by 0xCP** [comment]
> 这个最高支持到10.6.4

谢谢回答
