### ISSUE TITLE
完蛋了,之前的0.3版本正常

### ISSUE THREAD

**Issue by 277383761** [sifacaii/VlcJellyfin#2]
0.3版本在安卓4.4的盒子上使用正常.就是一些hdr视频会绿屏
这次的1.0.5版本在登陆emby后立即闪退,连试播的机会都没给.哈

**Comment by XG-China** [comment]
你Jellyfin是什么版本啊！我用的10.8.5不显示视频

**Comment by 277383761** [comment]
我用的是emby 4.6.4
